name: Testes

on:
  push:
    branches:
      - main  # ou qualquer outra branch que você deseja monitorar para testes

jobs:
  testes:
    runs-on: ubuntu-latest

    steps:
    - name: Download do Repositório
      uses: actions/checkout@v4

    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: 3.10

    - name: Instalação das dependências
      run: |
        pip install -r requirements.txt

    - name: Execução dos testes
      run: |
        print('teste de aplicação')
