name: avaliação do código - PyLint

on:
  push:
    branches:
      - main  # ou qualquer outra branch que você deseja monitorar para testes

jobs:
  pylint:
    name: Run pylint
    runs-on: ubuntu-latest
    outputs:
      pylint_result: ${{ steps.pylint.outputs.pylint_result }}

    steps:
    - name: Download repo
      uses: actions/checkout@v4

    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Setup pylint
      run: |
        pip install pylint

    - name: Pylint score
      id: resultado  
      run: |
        pylint_score=$(pylint app/python/scripts/get_data_v2.py | sed -n 's/^Your code has been rated at \([-0-9.]*\)\/.*/\1/p' )
        echo "Score pylint $pylint_score"
        if [ {{ $pylint_score }} >= 7 ]; then
          echo "sucess"
        else
          echo "failure"
        fi
      continue-on-error: true
  
  dockerhub:
    needs: pylint
    runs-on: ubuntu-latest
    if: ${{ success() && needs.pylint.outputs.resultado == 'success' }}
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: docker build -t rpadolfo/python-dataops:latest app/python/

      - name: Push Docker image to Docker Hub
        run: docker push rpadolfo/python-dataops:latest